html/interactive-guides/microprofile-config/download-from-properties-file.html, html/interactive-guides/microprofile-config/download-from-property-in-server-env.html, html/interactive-guides/microprofile-config/microprofile-config-guide.html, js/interactive-guides/microprofile-config/microprofile-config-callback.js, json-guides/microprofile-config.json
Add step to use server.env as a config source to override default property and property in microprofile-config.properties.
=> Add configureAsEnvVar as a new step

html/interactive-guides/microprofile-config/download-from-properties-file.html, json-guides/microprofile-config.json
Change save action to run and change ftp url to "canada" as we'll use "us" as the default.
=> Change Save to Run action

js/interactive-guides/microprofile-config/microprofile-config-callback.js, json-guides/microprofile-config.json
=> Enable mp config

json-guides/microprofile-config.json
=> Removed Dynamic Props and Converters from TOC

js/interactive-guides/microprofile-config/microprofile-config-callback.js, json-guides/microprofile-config.json
=> Added the 'Changing the ordinal of a ConfigSource' step

html/interactive-guides/microprofile-config/microprofile-config-guide.html, js/interactive-guides/microprofile-config/microprofile-config-callback.js, json-guides/microprofile-config.json
Updated the Title, guide description, TOC labels, text on the injection steps, and associated instruction processing.
=> Title, description, injection steps changes

html/interactive-guides/microprofile-config/playground.html, js/interactive-guides/microprofile-config/microprofile-config-callback.js, js/interactive-guides/microprofile-config/playground-callback.js, json-guides/microprofile-config.json
Connect the playground javascript to the editor in the playground step. No UI interaction yet.
=> Initial playground integration

json-guides/microprofile-config.json
Initial text for the Example scenario.
The configuration property that the user will be setting is a port value.
The scenario works the user through the devOps pipeline.  A microservice that lists available types of cars for purchase for some company is working its way through the devOps pipeline:
- Development
- Test
- Quality Assurance
- Production
The user only has to update configuration value for the port value to get the listing from a different microservice.  The guide will show the user how to easily reset this value.
=> Initial example scenario added

html/interactive-guides/microprofile-config/playground.html, js/interactive-guides/microprofile-config/playground-callback.js
Initial implementation of showing the final properties.
=> Show list of properties in pod.

js/interactive-guides/microprofile-config/microprofile-config-callback.js, json-guides/microprofile-config.json
Updates to You'll Learn and Background steps.
Updates to remove WLP_SKIP_MAX_PERMSIZE from files since it is not pertinent to our example.
=> Doc changes based on review 3

json-guides/microprofile-config.json
Updates for the example page from Michal.
Update 'runtime level' to be 'installation level' in the environment variable step.
=> Updates for the example

json-guides/microprofile-config.json
Reviewed changes for #4.   Small updates made as team to the text.
=> Small text updates to various pages

html/interactive-guides/microprofile-config/microprofile-config-guide.html
Fixes #65
Change url to `/guides/microprofile-config-intro.html`
=> Change the url of the guide

js/interactive-guides/microprofile-config/playground-callback.js, json-guides/microprofile-config.json
=> Rename tabbedEditor files. Rewording and improvments.

js/interactive-guides/microprofile-config/microprofile-config-callback.js, json-guides/microprofile-config.json
=> Added browser status bar text in json and callbacks

js/interactive-guides/microprofile-config/microprofile-config-callback.js, json-guides/microprofile-config.json
=> Changes to browser status bar text

js/interactive-guides/microprofile-config/microprofile-config-callback.js
Temporary fix to wait for the editors to load before reading their contents.
=> Wait 250ms before pulling from all of the editors in the playground

html/interactive-guides/microprofile-config/microprofile-config-guide.html
- Add the current date so that this guide is sorted as the most recently published guide.
=> Add release date

css/interactive-guides/microprofile-config/mpconfig.css, html/interactive-guides/microprofile-config/playground.html, js/interactive-guides/microprofile-config/playground-callback.js
=> Props table changes for text overflow and table width

html/interactive-guides/microprofile-config/playground.html, js/interactive-guides/microprofile-config/microprofile-config-callback.js, json-guides/microprofile-config.json
=> Accessibility fixes

css/interactive-guides/microprofile-config/mpconfig.css, html/interactive-guides/microprofile-config/playground.html, js/interactive-guides/microprofile-config/mpconfig-messages.js, js/interactive-guides/microprofile-config/playground-callback.js
=> Fixing DAP violations

json-guides/microprofile-config.json
Part of the for the spacing issue OpenLiberty/iguides-common#114
=> Remove unnecessary breaklines for OpenLiberty/iguides-common#114

html/interactive-guides/microprofile-config/microprofile-config-guide.html
=> Update title and description for MPConfig guide

css/interactive-guides/microprofile-config/mpconfig.css
Issue: this happens when hovering over some of the file cards
=> Fix ghost borders/shadows on the file cards.

js/interactive-guides/microprofile-config/microprofile-config-callback.js
I found this duplicate line while exploring a new tool to minify our javascript files.  The tool reported that it saw duplicate code.
=> Remove duplicate line

html/interactive-guides/microprofile-config/microprofile-config-guide.html
- Related to OpenLiberty/openliberty.io#287
=> Add new attributes for category organization design

css/interactive-guides/microprofile-config/mpconfig.css, json-guides/microprofile-config.json
Playground step:
- add instruction
- change pod height to 250px
- update css for the card and table in the pod
- for now, keep the web browser in it as inactive. Will discuss with the team whether to remove the web browser or not.
=> Add instruction to playground step

html/interactive-guides/microprofile-config/welcome.html, json-guides/microprofile-config.json
Use different URL for welcome page.
=> Welcome page to use different URL

json-guides/microprofile-config.json
didn't see anything other than "following browser" to correct
=> removes following in refrence to browser

js/interactive-guides/microprofile-config/microprofile-config-callback.js, json-guides/microprofile-config.json
add call to show updated icon in editor and remove bold styling in playground instruction
=> Show updated icon in editor

js/interactive-guides/microprofile-config/microprofile-config-callback.js, js/interactive-guides/microprofile-config/microprofile-config-guide.js, json-guides/microprofile-config.json
Reverts OpenLiberty/iguide-microprofile-config-intro#216
=> Revert "rename the mp link to the new repo"

json-guides/microprofile-config.json
Add reference to 'Open Liberty' to the title and text of the 'Enabling MicroProfile Fault Tolerance' step.
=> Update add FT step to include "Open Liberty"

json-guides/microprofile-config.json
Reference: https://github.com/OpenLiberty/iguides-common/issues/298
=> Default is Run now so no need to specify "save":false

html/microprofile-config-guide.html
=> change common message file
