OpenLiberty/iguide-microprofile-config-intro

js/interactive-guides/microprofile-config/microprofile-config-callback.js

Display browser side by side with editor instead of sliding in after run is clicked. Add codes to honor browser refresh only if current index is on the browser instruction.

Display browser side by side with editor 

---

json-guides/microprofile-config.json

fixes #1 
Moved the non-interactive information that was in the "Using default ConfigSources to provide configuration data" step to background concepts and moved out all the Configuring steps that appeared underneath this step out one level in the TOC.

Initial writeup on What youll learn and Background concepts

---

js/interactive-guides/microprofile-config/microprofile-config-callback.js

Since this is the opening step of seeing the 'application' in a browser, let the browser slide in.... on this step only.

Put back browser slide on default step

---

js/interactive-guides/microprofile-config/playground-callback.js

Keep trailing whitespace after the property value to stay true to properties file format spec.
Regex change to ignore any amount of white space in between the key and value.

Remove trim from property value.

---

css/interactive-guides/microprofile-config/mpconfig.css
json-guides/microprofile-config.json

Somehow the port settings in the bootstrap.properties and server.env files on the change ordinal page were missing their port settings.   Added them back in.
Lowered the font size of the sample app in the sample browser for the demo today.  Design is working on improving this page.

Change font size in sample web; Add ports to files on ordinal page

---

json-guides/microprofile-config.json

Emily indicates that 
"If the same property is specified in more than one microprofile-config.properties files, which file supplies the value is undetermined. In practice, the same config property should not occur in more than one microprofile-config.properties. If you want to determine its value, you should override it via system property or environment variables."
So, to the Configuring with a properties file page, add
The same config property should not be specified in multiple /META-INF/microprofile-config.properties files that have the same ordinal value as this would result in an indeterministic property value being returned.

Explain if prop is in more than one properties file on classpath

---

json-guides/microprofile-config.json

Text updates include:
- Update to background concepts, add text before the picture to indicate something about setting an optional default value so the bottom box in the diagram makes sense in that picture.
- Add text to the injection step to further define a mandatory property so that the user understands they are setting a mandatory property in this step's interaction and that the error that appears is expected.
- The instruction for the injection step should include 'mandatory' ....   'To inject a **mandatory** port configuration...'
- Change the title of the default step to 'Providing optional default values'

Updates to text as requested during review 5

---

js/interactive-guides/microprofile-config/microprofile-config-callback.js

After adding the code to have single editor widgets changed to being a single file in a tabbed editor (issue #95), the error message displayed on the injection step appeared to be displayed to high and looked out of place.  Add a margin to the top of the paragraph introducing the DeploymentException so it appears in a better location.

Move error msg on inject step down a bit

---

js/interactive-guides/microprofile-config/playground-callback.js

Old implementation only allowed for `name=` and `defaultValue=`.
Now allows for `name = ` and `defaultValue = ` with any whitespace

Fix annotation parameter checking to allow some whitespace.

---

finish/README.txt

The path to the Liberty server in the /finish/README.txt file specified 
..../wlp/user/servers
instead of
.../wlp/usr/servers.
Correct this!

Correct path to server specified in /finish/README.txt

---

js/interactive-guides/microprofile-config/playground-callback.js

When parsing the property key-value pair, remove injection codes put in by the user.

Fix playground to remove any injection code from the editor content

---

js/interactive-guides/microprofile-config/microprofile-config-callback.js
json-guides/microprofile-config.json

Remove tabbed editor listener. Instead force to the correct tabbed file name before adding the content through instruction.

Remove tabbed editor listener

---

css/interactive-guides/microprofile-config/mpconfig.css
html/interactive-guides/microprofile-config/playground.html
json-guides/microprofile-config.json

Review changes include:
- change car-inventory URL back to car-types
- playground step:
- center cards and table 
- add table border to multi column view similar to that of single column view
- allow more space for table row so that scrollbar won't come in until after 3 rows in multi column view.
- add scrollbar to the table - has to use display block to add scrollbar to the table. If display block is used, the table column formatting will not be honored. To workaround this problem, keep the table but put a wrapper around the table with display block on the wrapper. To make the scrollbar looking like part of the table, extend the width of the table to the full width to position the scrollbar clos to the table. If scrollbar position is still undesirable, then we should open an issue to …

Review changes

---

css/interactive-guides/microprofile-config/mpconfig.css
html/interactive-guides/microprofile-config/download-from-injection.html
html/interactive-guides/microprofile-config/download-from-properties-file.html
html/interactive-guides/microprofile-config/download-from-property-in-server-env.html
html/interactive-guides/microprofile-config/download-from-property-in-system-props.html
html/interactive-guides/microprofile-config/welcome.html
json-guides/microprofile-config.json

To fully display the various car types in the web browser in a mobile device such as iphone, the browser height has to be different from that of the height used by the multi column view. Add a new "singleColumnHeight" attribute for the webBrowser in the default configWidgets section in the json file. 
Also add an outer flex container to center the web browser contents.

Add singleColumnHeight attribute to webBrowser

---

js/interactive-guides/microprofile-config/microprofile-config-callback.js

When selecting the code insertion button in the instructions, make sure that the tabbedEditor is focused and the correct tab for the code being added.

Focus file prior to adding code via instruction button

---

json-guides/microprofile-config.json

To match other guides, Bold the non-clickable 'Run' reference in the playground instruction.

Bold 'Run' button reference in playground instruction

---

js/microprofile-config-callback.js
js/playground-callback.js

Handle multiple errors in one editor content, allow each editor to show its own error, and display code updated only with successful edit.

Support for each editor to have its own error

---

js/microprofile-config-callback.js

On the 'Enabling MicroProfile Config in Open Liberty' step, the error in the editor remains after the code action button in the instruction correctly updates the code in the editor and the user selects 'Run'.
Correct so that the error message is removed.

Remove editor error

---

js/microprofile-config-callback.js
js/nls/microprofile-config/messages.js
json-guides/microprofile-config.json

On the 'Injecting configuration through @ConfigProperty annotation' step an error panel is slid into view within a pod when 'Run' is selected.  Update so that the pod just shows without sliding in its contents.  Also, center the text so that there isn't a large space underneath the text.

Center error message shown in pod of Inject config step

---

css/microprofile-config/mpconfig.css

With browser zooming in to 50% or less, the text in the ordinal card is overflow. The fix is to hide the overflow in the card and show the full content when the card is hovered over.

Fix card overflow when using browser to zoom in

---

json-guides/microprofile-config.json

Update link to the 'Enabling MicroProfile Config in Open Liberty' step. It broke when we updated the title to the step to include 'in Open Liberty'.

Update link to the 'Enabling MicroProfile Config in Open Liberty' step.

---

js/microprofile-config-callback.js

In order for Reset to work correctly, we will save off the last successful (valid) save of the changes made to the editor widget, in all steps but the playground. The playground will always Reset to the original parameter values as seen on entry into the step.
For all the steps, after invoking `utils.validateContentAndSave()`, if the content was valid invoke `utils.saveContentInEditor()` to save away the updated content and update the editor's markText and markTextWritable arrays.
Utilized the new method from commons utils.js file, `utils.saveFeatureInContent()`, to save the contents of the server.xml file after it has been verified.

Reset processing for the Microprofile Config Intro guide
